packages:
  - packages/*
  - playground/*

catalog:
  '@arethetypeswrong/cli': ^0.18.2
  '@danielwaltz/eslint-config': ^2.5.1
  '@tsconfig/node22': ^22.0.2
  '@types/node': ~22.15.35
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.7.0
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/tsconfig': ^0.7.0
  automd: ^0.4.0
  changelogen: ^0.6.2
  eslint: ^9.32.0
  prettier: ^3.6.2
  publint: ^0.3.12
  react: ^19.1.0
  react-dom: ^19.1.0
  tsdown: ^0.13.0
  typescript: ~5.8.3
  unplugin-vue: ^7.0.0
  vite: ^7.0.6
  vue: ^3.5.18
  vue-tsc: ^3.0.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
