packages:
  - packages/*
  - playground/*
  - test

catalog:
  '@arethetypeswrong/cli': ^0.18.2
  '@danielwaltz/eslint-config': ^2.6.0
  '@sveltejs/vite-plugin-svelte': ^6.1.4
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.8.0
  '@testing-library/react': ^16.3.0
  '@testing-library/svelte': ^5.2.8
  '@testing-library/user-event': ^14.6.1
  '@testing-library/vue': ^8.1.0
  '@tsconfig/node22': ^22.0.2
  '@tsconfig/svelte': ^5.0.5
  '@types/node': ~22.17.2
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.2
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.8.1
  changelogen: ^0.6.2
  eslint: ^9.34.0
  happy-dom: ^18.0.1
  prettier: ^3.6.2
  publint: ^0.3.12
  react: ^19.1.1
  react-dom: ^19.1.1
  svelte: ^5.38.7
  svelte-check: ^4.3.1
  tsdown: ^0.14.2
  typescript: ~5.9.2
  vite: ^7.1.4
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-tsc: ^3.0.6

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
